# Generated by Django 4.0.1 on 2024-09-29 15:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kennels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('kennel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_dogs', to='kennels.kennel')),
            ],
            options={
                'verbose_name_plural': 'Adoption Dogs',
            },
        ),
    ]
