# Generated by Django 4.0.1 on 2024-09-29 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionDogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptiondog',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='adoptiondog',
            name='breed',
            field=models.CharField(default='Beagle', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptiondog',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptiondog',
            name='extra_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptiondog',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptiondog',
            name='good_with_cats',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptiondog',
            name='good_with_children',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptiondog',
            name='good_with_dogs',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptiondog',
            name='is_crossbreed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptiondog',
            name='size',
            field=models.CharField(choices=[('XS', 'x-small'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'x-large')], default='Medium', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptiondog',
            name='weight',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
