# Generated by Django 4.0.1 on 2024-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionDogs', '0002_adoptiondog_age_adoptiondog_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptiondog',
            name='breed',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='adoptiondog',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='adoptiondog',
            name='good_with_cats',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='adoptiondog',
            name='good_with_children',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='adoptiondog',
            name='good_with_dogs',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='adoptiondog',
            name='size',
            field=models.CharField(choices=[('XS', 'x-small'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'x-large')], max_length=16, null=True),
        ),
    ]
