# Generated by Django 4.0.1 on 2025-08-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_kennel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kennel',
            options={'ordering': ['name'], 'verbose_name': 'Kennel', 'verbose_name_plural': 'Kennels'},
        ),
        migrations.AddField(
            model_name='kennel',
            name='reset_password',
            field=models.BooleanField(default=True),
        ),
    ]
