# Generated by Django 4.0.1 on 2025-10-04 13:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name of the person contacting', max_length=255)),
                ('email', models.EmailField(help_text='Email address for contact', max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('contact_number', models.CharField(help_text='Phone number for contact', max_length=20)),
                ('address_line_1', models.CharField(blank=True, help_text='First line of address', max_length=255, null=True)),
                ('town', models.CharField(blank=True, help_text='Town or locality', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20, null=True)),
                ('contact_type', models.CharField(choices=[('general', 'General Contact'), ('rescue_signup', 'Rescue Center Signup'), ('adoption_inquiry', 'Adoption Inquiry'), ('support', 'Support Request'), ('other', 'Other')], default='general', help_text='Type of contact submission', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Subject of the contact', max_length=255, null=True)),
                ('message', models.TextField(help_text='Main message content')),
                ('is_actioned', models.BooleanField(default=False, help_text='Whether this contact has been actioned by admin')),
                ('actioned_at', models.DateTimeField(blank=True, help_text='When this contact was actioned', null=True)),
                ('action_notes', models.TextField(blank=True, help_text='Notes about the action taken', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of this contact', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the submitter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request', null=True)),
                ('follow_up_required', models.BooleanField(default=False, help_text='Whether a follow-up is required')),
                ('follow_up_date', models.DateTimeField(blank=True, help_text='Scheduled follow-up date', null=True)),
                ('actioned_by', models.ForeignKey(blank=True, help_text='Admin user who actioned this contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created', '-priority'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_type', 'is_actioned'], name='contact_con_contact_2b3ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['priority', 'created'], name='contact_con_priorit_f654cb_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='contact_con_email_2ebc86_idx'),
        ),
    ]
