# Generated by Django 4.0.1 on 2024-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0002_kennel_contact_number_kennel_email_kennel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kennel',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='kennel',
            name='location',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
