# Generated by Django 4.0.1 on 2025-10-05 13:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Category name (e.g., 'Adoption Stories', 'Dog Care')", max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the category', null=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for category display', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active and visible')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Tag name (e.g., 'puppy', 'training', 'health')", max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the tag', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tag is active and visible')),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Blog post title', max_length=255, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt or summary of the post', max_length=500, null=True)),
                ('content', models.TextField(help_text='Main content of the blog post')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status of the post', max_length=20)),
                ('featured', models.CharField(choices=[('normal', 'Normal'), ('featured', 'Featured'), ('hero', 'Hero')], default='normal', help_text='Featured status of the post', max_length=20)),
                ('is_published', models.BooleanField(default=False, help_text='Whether the post is published and visible')),
                ('published_at', models.DateTimeField(blank=True, help_text='When the post was published', null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When the post is scheduled to be published', null=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (if different from title)', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', max_length=160, null=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to='blog/images/')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed')),
                ('like_count', models.PositiveIntegerField(default=0, help_text='Number of likes this post has received')),
                ('allow_comments', models.BooleanField(default=True, help_text='Whether comments are allowed on this post')),
                ('comment_count', models.PositiveIntegerField(default=0, help_text='Number of comments on this post')),
                ('reading_time_minutes', models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes')),
                ('author', models.ForeignKey(help_text='Author of the blog post', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Category this post belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with this post', related_name='posts', to='blog.BlogTag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(help_text='Name of the comment author', max_length=100)),
                ('author_email', models.EmailField(help_text='Email of the comment author', max_length=254)),
                ('content', models.TextField(help_text='Comment content', validators=[django.core.validators.MinLengthValidator(10)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('spam', 'Spam')], default='pending', help_text='Moderation status of the comment', max_length=20)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this comment is approved and visible')),
                ('moderated_at', models.DateTimeField(blank=True, help_text='When this comment was moderated', null=True)),
                ('moderation_notes', models.TextField(blank=True, help_text='Notes about the moderation decision', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the commenter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request', null=True)),
                ('moderated_by', models.ForeignKey(blank=True, help_text='Admin who moderated this comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_comments', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.blogcomment')),
                ('post', models.ForeignKey(help_text='Blog post this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'is_published'], name='blog_blogpo_status_a46de1_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['published_at'], name='blog_blogpo_publish_9c2556_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['featured', 'published_at'], name='blog_blogpo_feature_e75a47_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author', 'status'], name='blog_blogpo_author__e8757b_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['post', 'status'], name='blog_blogco_post_id_5f3ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['status', 'is_approved'], name='blog_blogco_status_8153f2_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['author_email'], name='blog_blogco_author__8ad1cd_idx'),
        ),
    ]
