# Generated by Django 4.0.1 on 2025-10-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'puppy, training, health')", max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='BlogTag',
        ),
    ]
