# Generated by Django 4.0.1 on 2025-10-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_tags_blogpost_tags_delete_blogtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, help_text="Category name (e.g., 'Adoption Stories', 'Dog Care Tips')", max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
