# Generated by Django 4.0.1 on 2025-10-05 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_blogpost_category_delete_blogcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='moderated_by',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='post',
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created']},
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_status_a46de1_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_publish_9c2556_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_feature_e75a47_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_author__e8757b_idx',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='allow_comments',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='reading_time_minutes',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='status',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
