# Generated by Django 4.0.1 on 2026-04-10 10:00

from django.db import migrations, models
import neoProject.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogpost_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=neoProject.upload_paths.CloudinaryFolderPath("blog"),
            ),
        ),
    ]
