# Generated by Django 4.0.1 on 2025-10-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Secondary product image', null=True, upload_to='shop/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Third product image', null=True, upload_to='shop/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Fourth product image', null=True, upload_to='shop/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='shop/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Dog Food'), ('TOYS', 'Toys'), ('ACCESSORIES', 'Accessories'), ('HEALTH', 'Health & Wellness'), ('GROOMING', 'Grooming'), ('TRAINING', 'Training'), ('BEDDING', 'Bedding'), ('TRAVEL', 'Travel'), ('SAFETY', 'Safety'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
