# Generated by Django 4.0.1 on 2025-10-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_add_session_support_to_orders'),
    ]

    operations = [
        # Remove constraints first
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_user_product_cart',
        ),
        # Remove the discount_amount field from Order
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        # Delete the CartItem model
        migrations.DeleteModel(
            name='CartItem',
        ),
        # Delete the Coupon model
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]