# Generated by Django 4.0.1 on 2026-04-10 10:00

from django.db import migrations, models
import neoProject.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ("breeds", "0008_alter_breed_lifespan_height_weight_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="landscape_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=neoProject.upload_paths.CloudinaryFolderPath("breeds"),
            ),
        ),
        migrations.AlterField(
            model_name="breed",
            name="portrait_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=neoProject.upload_paths.CloudinaryFolderPath("breeds"),
            ),
        ),
    ]
