# Generated by Django 4.0.1 on 2024-11-10 14:51

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=16, null=True)),
                ('age', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
                ('size', models.CharField(choices=[('XS', 'x-small'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'x-large')], max_length=16, null=True)),
                ('weight', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('good_with_dogs', models.BooleanField(null=True)),
                ('good_with_cats', models.BooleanField(null=True)),
                ('good_with_children', models.BooleanField(null=True)),
                ('breed', models.CharField(max_length=32, null=True)),
                ('is_crossbreed', models.BooleanField()),
                ('extra_information', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='adoption/dog/images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
