# Generated by Django 4.0.1 on 2025-10-17 12:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoption_dog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['-created'], 'verbose_name': 'Dog', 'verbose_name_plural': 'Dogs'},
        ),
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age in years (0-30)', null=True, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(blank=True, help_text="Dog's breed", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='extra_information',
            field=models.TextField(blank=True, help_text='Additional information about the dog', null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], help_text="Dog's gender", max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='good_with_cats',
            field=models.BooleanField(blank=True, help_text='Whether the dog gets along with cats', null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='good_with_children',
            field=models.BooleanField(blank=True, help_text='Whether the dog is good with children', null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='good_with_dogs',
            field=models.BooleanField(blank=True, help_text='Whether the dog gets along with other dogs', null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, help_text="Dog's photo", null=True, upload_to='adoption/dog/images'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='is_crossbreed',
            field=models.BooleanField(blank=True, help_text='Whether the dog is a crossbreed', null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='kennel',
            field=models.ForeignKey(help_text='Kennel that owns this dog', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(help_text="Dog's name", max_length=32),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'x-small'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'x-large')], help_text="Dog's size category", max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Weight in kg (1-200)', null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)]),
        ),
    ]
