# Generated by Django 4.0.1 on 2025-11-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_dog', '0003_alter_dog_options_alter_dog_age_alter_dog_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image2',
            field=models.ImageField(blank=True, help_text="Dog's second photo", null=True, upload_to='adoption/dog/images'),
        ),
        migrations.AddField(
            model_name='dog',
            name='image3',
            field=models.ImageField(blank=True, help_text="Dog's third photo", null=True, upload_to='adoption/dog/images'),
        ),
    ]
