# Generated by Django 4.0.1 on 2026-04-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_dog', '0004_dog_image2_dog_image3'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['age'], name='dog_match_age'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['weight'], name='dog_match_weight'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['good_with_children'], name='dog_match_gwc'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['good_with_dogs'], name='dog_match_gwd'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['good_with_cats'], name='dog_match_gwcats'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['is_crossbreed'], name='dog_match_cross'),
        ),
    ]
