# Generated by Django 4.0.1 on 2026-04-10 10:00

from django.db import migrations, models
import neoProject.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ("adoption_dog", "0005_dog_match_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Dog's photo",
                null=True,
                upload_to=neoProject.upload_paths.CloudinaryFolderPath("adoptDogs"),
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="image2",
            field=models.ImageField(
                blank=True,
                help_text="Dog's second photo",
                null=True,
                upload_to=neoProject.upload_paths.CloudinaryFolderPath("adoptDogs"),
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="image3",
            field=models.ImageField(
                blank=True,
                help_text="Dog's third photo",
                null=True,
                upload_to=neoProject.upload_paths.CloudinaryFolderPath("adoptDogs"),
            ),
        ),
    ]
